version: '{build}'

branches:
  only:
    - master

image: Visual Studio 2015

install:
  - git submodule init
  - git submodule update
  - ps: $env:SUFFIX = $(git log -1 --format=%cd-%h --date=format:%Y%m%d-%H%M%S $env:APPVEYOR_REPO_COMMIT)
  - ps: $env:TIMESTAMP = $(git log -1 --format=%cd --date=format:%Y%m%d-%H%M%S $env:APPVEYOR_REPO_COMMIT)
  - ps: $env:RELEASE_NAME = "b2-"+$env:SUFFIX
  - ps: $env:OUTPUT_NAME = "b2-windows-"+$env:SUFFIX+".zip"
  
build_script:
  - "echo OUTPUT_NAME: %OUTPUT_NAME%"
  - python ./etc/release/release.py --timestamp=%TIMESTAMP% --make=./snmake.exe %SUFFIX%
  # this seems like the easiest way of getting rid of the folder structure...
  - copy build\_Rel\win32\%OUTPUT_NAME% %OUTPUT_NAME%

artifacts:
  - path: $(OUTPUT_NAME)
    name: output

deploy:
  - release: $(RELEASE_NAME)
    description: 'b2'
    provider: GitHub
    auth_token:
      secure: NTWtNQsxaMVhAyad5bBM3H6lTGsqRCprICrq8kvYvXgjnaeDcjjLpNe0H0ZaG4sl
    artifact: output
    draft: false
    prerelease: false
    on:
      branch: master
